version: '3.8'

services:
  vds:
    build: ./vds
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./vds/.env
    restart: unless-stopped
    volumes:
      - vds_data:/app/data
      - vds_logs:/app/logs

  vts:
    build: ./vts
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    env_file:
      - ./vts/.env
    restart: unless-stopped
    volumes:
      - vts_logs:/app/logs
    depends_on:
      - vds

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - vds
      - vts
    restart: unless-stopped

volumes:
  vds_data:
  vds_logs:
  vts_logs:
